# Setup
title:        ECIS 2017 - Similarity Workshop
tagline:      June 6th, 2017 - Guimarães, Portugal
baseurl:      ""
#paginate:     1

# About/contact
author:
  name:       Mahmood Shafeie Zargar
  url:        http://retrography.github.io/similarity-workshop

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge
