# Setup
title:        ECIS 2017 - Similarity Workshop
tagline:      A workshop that helps you discover the treasure in your data
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Mahmood Shafeie Zargar
  url:        http://retrography.github.io/similarity-workshop

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
highlighter: rouge